[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "echo \"Railway PORT: $PORT\" && echo \"Environment vars:\" && env | grep -E '^(PORT|NODE_ENV|TRANSPORT)' && node build/index.js --transport http --host 0.0.0.0"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
TRANSPORT = "http"
HOST = "0.0.0.0"
DEBUG = "false"