[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node build/index.js --transport http --port $PORT --host 0.0.0.0"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
TRANSPORT = "http"
HOST = "0.0.0.0"
DEBUG = "false"